ProyectoMVCFramework1/ProyectoMVCFramework1/Models/Login.cs
using ProyectoMVCFramework1.Validation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Drawing;
using System.Linq;
using System.Web;

namespace ProyectoMVCFramework1.Models
{
    public class Login
    {
        [Required]
        [EmailAddress(ErrorMessage = "Usernames must be a valid email address.")]
        public string Username { get; set; }

        [Required]
        [MinLength(8, ErrorMessage = "This password is too short.")]
        [CommonPasswords(ErrorMessage = "This Password is too common.")]
        public string Password { get; set; }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Models/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProyectoMVCFramework1.Models
{
    public class Product
    {
        public string Name { get; set; }
        public decimal FullPrice { get; set; }
        public decimal CurrentPrice { get; set; }
        public int PercentOff { get; set; }
        public string ImagePath { get; set; }
        public int StarRating { get; set; }

    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/AccountController.cs
using ProyectoMVCFramework1.Data;
using ProyectoMVCFramework1.Data.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    [Authorize] //Es un filtro que pide al user estar autorizado para acceder a este contenido//
    public class AccountController : Controller
    {
        // GET: Account
        public ActionResult Index()
        {
            Customer customer = null;
            using (var ctx = new HPlusSportDbContext()) {
                var user = ctx.Users.FirstOrDefault(u=>u.EmailAddress == User.Identity.Name);

                if (user != null)
                    customer = ctx.Customers.FirstOrDefault(c=>c.CustomerID == user.CustomerId);

            }

           return View(customer);
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/HelloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    public class HelloController : Controller
    {
        // GET: Hello
        public ActionResult Index()
        {
            return View();
            
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/HomeController.cs
using ProyectoMVCFramework1.Filters;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    [CrawlerFilter] //Agrega el filtro a este controlador
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            //throw new System.Exception(); //Para probar el filtro de excepciones
            return View();
        }

    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/LoginController.cs
using Microsoft.Ajax.Utilities;
using ProyectoMVCFramework1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ProyectoMVCFramework1.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()//
        {
            return View();
        }

        [HttpPost] //Porque el método del formulario es Post
        public ActionResult Index(Models.Login request) 
        {
            if (!ModelState.IsValid) return View(request);//Se activa si cualquier anotación del modelo no se cumple

            if (!string.IsNullOrEmpty(request.Username) && !string.IsNullOrEmpty(request.Password))
            {
                FormsAuthentication.SetAuthCookie(request.Username, false); //Seteamos la cookie de auth con username y false para que expire con la sesión
                return Redirect(FormsAuthentication.GetRedirectUrl(request.Username, false));
            }
            ViewBag.Failed = true; 
            return View(request); //Envía el modelo de regreso a la vista :D 
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/ProductController.cs
using ProyectoMVCFramework1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product 

        public ActionResult Index()
        {
            return View("Index"); //De esta manera puedo definir el nombre de la view dentro de la carpeta del nombre del controlador
            //o si es por fuera de la carpeta con algo tipo "~Views/Product/Nombre_de_la_vista.cshtml"
        }

        [Route("product/{productName}")]
        public ActionResult Detail(string productName)
        {
            ViewBag.Product = new Product {
                Name = "Women´s winter jacket",
                FullPrice = 20.00M,
                CurrentPrice = 16.00M,
                PercentOff = 20,
                ImagePath = "/Content/Images/Products/1.jpg",
                StarRating = 2
            }; //Agregamos un objeto tipo producto al ViewBag :D 
            return View();
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProyectoMVCFramework1.Controllers
{
    public class ProductsController : Controller
    {
        // GET: Products
        public ActionResult Index()
        {
            //Es un ejemplo para aplicar redirección
            //Supongamos que el sitio en una versión anterior tenía un apartado PRODUCTS en vez de PRODUCT
            //Con este controlador resolvemos ese problema, redireccionando PRODUCTS a PRODUCT
            return RedirectToAction("Index","Product"); //Sirve para redireccionar al método de otro controlador
            //Es Método, Controlador
        }
    }
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Cart/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutNoFooter.cshtml";
}

<h3 class="h3">Cart</h3>

<div class="row">
    <div class="col-12">
        <div class="table">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col"> </th>
                        <th scope="col">Product</th>
                        <th scope="col">Available</th>
                        <th scope="col" class="text-center">Quantity</th>
                        <th scope="col" class="text-right">Price</th>
                        <th> </th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Dada</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$124.90</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Toto</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$33.90</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td><img src="https://dummyimage.com/50x50/55595c/fff" /> </td>
                        <td>Product Name Titi</td>
                        <td>In stock</td>
                        <td><input class="form-control" type="text" value="1" /></td>
                        <td class="text-right">$70.00</td>
                        <td class="text-right"><button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> </button> </td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Sub-Total</td>
                        <td class="text-right">$255.90</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td>Shipping</td>
                        <td class="text-right">$6.90</td>
                    </tr>
                    <tr>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td><strong>Total</strong></td>
                        <td class="text-right"><strong>$346.90</strong></td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4 col-lg-offset-1">
        <a href='@Url.Action("Index", "Product")' class="btn btn-primary btn-lg btn-block" role="button">Continue Shopping</a>
    </div>
    <div class="col-lg-4 col-lg-offset-2">
        <a class="btn btn-lg btn-block btn-success text-uppercase" role="button">Checkout</a>
    </div>
</div>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Hello/Index.cshtml
<h2>HELLO</h2>
<br />
<br />
<h3>Esta es la vista Index del HelloController</h3>    

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <div class="jumbotron-content">
        <h1>H+ Sport</h1>
        <p class="lead">We’re committed to creating products that defy convention, and inspire our customers with pride and trust. In fact, we guarantee every product we sell. If you’re not 100 percent happy with your purchase, you can return it during the first 60 days, no questions asked.</p>
        <p><a href="@Url.Action("Index", "Product")" class="btn btn-primary btn-lg">Our Products &raquo;</a></p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Philosophy</h2>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean pulvinar vel metus in vestibulum. Cras placerat libero at quam scelerisque rhoncus. Nam porta, orci eu maximus consequat, leo lectus lacinia neque, non mattis lorem nisi non ligula. Aliquam tristique enim at turpis euismod, vitae iaculis turpis gravida.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>History</h2>
        <p>Pellentesque convallis mi at ex aliquet, quis condimentum lacus efficitur. Maecenas at dolor mattis sem vestibulum blandit. Donec pretium, nisl ut interdum fringilla, tellus justo pharetra neque, in porttitor tortor orci a urna. Vivamus at mauris mauris. Etiam nec orci vitae nisi laoreet efficitur. Maecenas rhoncus justo tellus, ut lacinia lacus mollis non.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>People</h2>
        <p>Phasellus molestie egestas lorem, ut imperdiet mauris auctor quis. In lacinia, mi non imperdiet suscipit, odio metus facilisis nunc, sit amet consequat lectus tellus at orci. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Suspendisse potenti.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

@section scripts
{
    <h2>Hello sections! :D</h2>
}

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Login/Index.cshtml
@model ProyectoMVCFramework1.Models.Login

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="container">

        @using (Html.BeginForm("Index", "Login", new { ReturnUrl = Request.QueryString["ReturnUrl"] }, FormMethod.Post, new { @class = "form-signin" }))
        {
            if (IsPost)
            {
                <div class="alert alert-danger">@Html.ValidationSummary()</div>
            }
            <h2 class="form-signin-heading">Please sign in</h2>
            @Html.LabelFor(m => m.Username, "Email address", new { @class = "control-label" })
            @Html.TextBoxFor(m => m.Username, new { @class = "form-control", placeholder = "Email Address", autofocus = "" })
            @Html.ValidationMessageFor(m => m.Username)
            <label for="password" class="sr-only">Password</label>
            <input type="password" id="password" name="password" class="form-control" placeholder="Password">
            @Html.ValidationMessageFor(m => m.Password)
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        }

    </div>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Product/Detail.cshtml
@{
    ViewBag.Title = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
@*<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />*@

<div class="container">
    <h3 class="h3">Our Products</h3>
    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <div class="product-grid">
                <div class="product-image">
                    <a href="#">
                        <img src="@ViewBag.Product.ImagePath">
                    </a>
                    <ul class="social">
                        <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                        <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                        <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                    </ul>
                    <span class="product-new-label">Sale</span>
                    <span class="product-discount-label">20%</span>
                </div>
                <ul class="rating">
                    @for (var i = 1; i <= ViewBag.Product.StarRating; i++)
                    {
                        <li class="fa fa-star"></li>
                    }
                    @for (var i = ViewBag.Product.StarRating; i < 5; i++)
                    {
                        <li class="fa fa-star disable"></li>
                    }
                </ul>
                <div class="product-content">
                    <h3 class="title"><a href="#">@ViewBag.Product.Name</a></h3>
                    <div class="price">
                        @ViewBag.Product.CurrentPrice
                        <span>@ViewBag.Product.FullPrice</span>
                    </div>
                    <a class="add-to-cart" href="">+ Add To Cart</a>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 
<h3 class="h3">Our Products</h3>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/1.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">20%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star disable"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-winter-jacket">Women's Winter Jacket</a></h3>
                <div class="price">
                    $16.00
                    <span>$20.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/2.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-pants">Women's Pants</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/3.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/mens-jeans">Men's Jeans</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/4.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-rain-jacket">Women's Rain Jacket</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/5.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">20%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star disable"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-hiking-jacket">Women's Hiking Jacket</a></h3>
                <div class="price">
                    $16.00
                    <span>$20.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/6.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-sweater">Women's Sweater</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/7.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/mens-plain-tshirt">Men's Plain Tshirt</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
    <div class="col-md-3 col-sm-6">
        <div class="product-grid">
            <div class="product-image">
                <a href="#">
                    <img src="~/Content/Images/Products/8.jpg">
                </a>
                <ul class="social">
                    <li><a href="" data-tip="Quick View"><i class="fa fa-search"></i></a></li>
                    <li><a href="" data-tip="Add to Wishlist"><i class="fa fa-shopping-bag"></i></a></li>
                    <li><a href="" data-tip="Add to Cart"><i class="fa fa-shopping-cart"></i></a></li>
                </ul>
                <span class="product-new-label">Sale</span>
                <span class="product-discount-label">50%</span>
            </div>
            <ul class="rating">
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
                <li class="fa fa-star"></li>
            </ul>
            <div class="product-content">
                <h3 class="title"><a href="/product/womens-polo">Men's Polo</a></h3>
                <div class="price">
                    $5.00
                    <span>$10.00</span>
                </div>
                <a class="add-to-cart" href="">+ Add To Cart</a>
            </div>
        </div>
    </div>
</div>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="icon" href="~/Content/images/icons/32x32.png" sizes="32x32">
    <link rel="icon" href="~/Content/images/icons/192x192.png" sizes="192x192">
</head>
<body>
    @Html.Partial("~/Views/Shared/_NavBar.cshtml")
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; H+ Sport @DateTime.Now.Year</p> *@
            @*Con el metodo de extensión que creamos sería...*@
            @Html.Copyright() |
            Twitter: <a href="https://twitter.com/hplussport" target="_blank"> @@HplusSport </a>
            @Html.Saludo()
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Shared/_LayoutNoFooter.cshtml
@helper IconBars(int count) 
{
    for (var i = 0; i < count; i++)
    {
        <span class="icon-bar"></span>
    }
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="icon" href="~/Content/images/icons/32x32.png" sizes="32x32">
    <link rel="icon" href="~/Content/images/icons/192x192.png" sizes="192x192">
</head>
<body>
    @Html.Partial("~/Views/Shared/_NavBar.cshtml")
    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

ProyectoMVCFramework1/ProyectoMVCFramework1/Views/Shared/_NavBar.cshtml
@helper IconBars(int count)
{
    for (var i = 0; i < count; i++)
    {
        <span class="icon-bar"></span>
    }
}
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                @IconBars(3)
            </button>
            <a href='@Url.Action("Index", "Home")' class="navbar-brand">
                <div class="hplus-logo"></div>
            </a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Our Products", "Index", "Product")</li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href='@Url.Action("Index", "Cart")'><i class="fa fa-shopping-cart"></i> Cart</a></li>
            </ul>
        </div>
    </div>
</div>