CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Models/ApplicationDbContext.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace CRUDEmployee_MVC_Core.Models
{
    public class ApplicationDbContext : DbContext 
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options) : base(options)  
        { 
        }

        public DbSet<Employee> Employee { get; set; }
        //<Entity> y el nombre debe ser el nombre de la tabla en la BD

    }
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace CRUDEmployee_MVC_Core.Models
{
    public class Employee
    {
        [Key]
        public int Empid { get; set; }

        [Required(ErrorMessage = "Enter the employee name")]
        [Display(Name = "Employee Name")]
        public string Empname { get; set; }

        [Required(ErrorMessage = "Enter the employee email")]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Enter a valid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Enter the employee age")]
        [Display(Name = "Age")]
        [Range(20,50)]
        public int Age { get; set; }

        [Required(ErrorMessage = "Enter the employee salary")]
        [Display(Name = "Salary")]
        public int Salary { get; set; }
    }
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Models/ErrorViewModel.cs
using System;

namespace CRUDEmployee_MVC_Core.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CRUDEmployee_MVC_Core.Models;
using Microsoft.EntityFrameworkCore;

namespace CRUDEmployee_MVC_Core.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly ApplicationDbContext _db; //Para acceder a la base de datos por medio de EF

        public EmployeeController(ApplicationDbContext db) //Constructor
        {
            _db = db;
        }

        public IActionResult Index() //En INDEX haremos que liste a todos los empleados en la BD (READ)
        {
            var displaydata = _db.Employee.ToList();
            return View(displaydata);
        }

        [HttpGet]
        public async Task<IActionResult> Index(string empSearch) 
        {
            ViewData["GetEmployeesDetails"] = empSearch;//Dato compartido con la vista
            var empquery = from x in _db.Employee select x; //Query de EF, de la tabla Employee almacena en x
            if (!String.IsNullOrEmpty(empSearch))
            {
                empquery = empquery.Where(x=>x.Empname.Contains(empSearch)|| x.Email.Contains(empSearch)); //Agrega claususla Where
            }
            return View(await empquery.AsNoTracking().ToListAsync()); //Retorna el resultado del query como una lista asincrona que no pasa por _db
        }

        public IActionResult Create() // Http get, para mostrar la vista de crear
        {
            return View();
        }

        [HttpPost] //Http post, para guardar los datos en la BD
        public async Task<IActionResult> Create(Employee nEmp)//Es async para no recargar la página inmediatamente 
        {
            if (ModelState.IsValid) //Si no hay errores con los DataAnnotations...
            {
                _db.Add(nEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(nEmp);
        }

        public async Task<IActionResult> Edit(int? id) //Async porque debe buscar en la BD
        {
            if (id==null) 
            {
                return RedirectToAction("Index");
            }
            var getEmpDetails = await _db.Employee.FindAsync(id);
            return View(getEmpDetails);
        }

        [HttpPost] 
        public async Task<IActionResult> Edit(Employee oldEmp)
        {
            if (ModelState.IsValid)
            {
                _db.Update(oldEmp);
                await _db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(oldEmp);
        }

        public async Task<IActionResult> Detail(int? id) 
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDetails = await _db.Employee.FindAsync(id);
            return View(getEmpDetails);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            var getEmpDetails = await _db.Employee.FindAsync(id);
            return View(getEmpDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            var getEmpDetails = await _db.Employee.FindAsync(id);
            _db.Employee.Remove(getEmpDetails);
            await _db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

    }
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Employee/Create.cshtml
@model CRUDEmployee_MVC_Core.Models.Employee

@{
    ViewData["Title"] = "Create";
}

<h1>Create New Employee</h1>

<h4>Employee Data: </h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Employee/Delete.cshtml
@model CRUDEmployee_MVC_Core.Models.Employee

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Employee</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Employee/Detail.cshtml
@model CRUDEmployee_MVC_Core.Models.Employee

@{
    ViewData["Title"] = "Detail";
}

<h1>Employee's Detail</h1>

<div>
    <h4>Employee Data:</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empid)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Empid  }) |
    <a asp-action="Index">Back to List</a>
</div>

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Employee/Edit.cshtml
@model CRUDEmployee_MVC_Core.Models.Employee

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Employee</h1>

<h4>Employee Data:</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Empid" class="control-label"></label>
                <input asp-for="Empid" class="form-control" readonly />
                <span asp-validation-for="Empid" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Empname" class="control-label"></label>
                <input asp-for="Empname" class="form-control" />
                <span asp-validation-for="Empname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Age" class="control-label"></label>
                <input asp-for="Age" class="form-control" />
                <span asp-validation-for="Age" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label"></label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Employee/Index.cshtml
@model IEnumerable<CRUDEmployee_MVC_Core.Models.Employee>

@{
    ViewData["Title"] = "Index";
}

<h1>Employee CRUD</h1>

<p>
    <a asp-action="Create">New Employee</a>
</p>

<form asp-action="Index" method="get">
    <p>
        <input type="search" placeholder="Enter Employee Name or Email ...." name="empSearch" value="@ViewData["GetEmployeesDetails"]" style="width:500px;"/>
        <input type="submit" value="Search" class="btn btn-primary" /> |
        <a asp-action="Index">Get All Employees</a>
    </p>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Empid)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Age)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Empid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Age)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Empid}, new { @class="btn btn-primary" }) |
                @Html.ActionLink("Details", "Detail", new { id = item.Empid }, new { @class = "btn btn-success" }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Empid }, new { @class = "btn btn-danger" })
            </td>
        </tr>
}
    </tbody>
</table>

CRUDEmployee_MVC_Core/CRUDEmployee_MVC_Core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CRUDEmployee_MVC_Core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CRUDEmployee_MVC_Core</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CRUDEmployee_MVC_Core 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>